const Mark = [
    {
        id : "1",
        sub1 : "Tamil",
        sub2 : "English",
        sub3 : "Maths",
        sub4 : "Science",
        sub5 : "SocialScience",
        sub6 : "Hindi",
        sub7 : "ComputerScience" 
    },
    {
        id : "2",
        sub1 : "Tamil",
        sub2 : "English",
        sub3 : "Maths",
        sub4 : "Science",
        sub5 : "SocialScience",
        sub6 : "Hindi",
        sub7 : "ComputerScience" 
    },
    {
        id : "3",
        sub1 : "Tamil",
        sub2 : "English",
        sub3 : "Maths",
        sub4 : "Science",
        sub5 : "SocialScience",
        sub6 : "Hindi",
        sub7 : "ComputerScience" 
    },
    {
        id : "4",
        sub1 : "Tamil",
        sub2 : "English",
        sub3 : "Maths",
        sub4 : "Science",
        sub5 : "SocialScience",
        sub6 : "Hindi",
        sub7 : "ComputerScience" 
    },
    {
        id : "5",
        sub1 : "Tamil",
        sub2 : "English",
        sub3 : "Maths",
        sub4 : "Science",
        sub5 : "SocialScience",
        sub6 : "Hindi",
        sub7 : "ComputerScience" 
    },
    {
        id : "6",
        sub1 : "Tamil",
        sub2 : "English",
        sub3 : "Maths",
        sub4 : "Science",
        sub5 : "SocialScience",
    },
    {
        id : "7",
        sub1 : "Tamil",
        sub2 : "English",
        sub3 : "Maths",
        sub4 : "Science",
        sub5 : "SocialScience",
    },
    {
        id : "8",
        sub1 : "Tamil",
        sub2 : "English",
        sub3 : "Maths",
        sub4 : "Science",
        sub5 : "SocialScience",
    },
    {
        id : "9",
        sub1 : "Tamil",
        sub2 : "English",
        sub3 : "Maths",
        sub4 : "Science",
        sub5 : "SocialScience",
    },
    {
        id : "10",
        sub1 : "Tamil",
        sub2 : "English",
        sub3 : "Maths",
        sub4 : "Science",
        sub5 : "SocialScience",
    },
    {
        id : "LKG",
        sub1 : "Tamil",
        sub2 : "English",
        sub3 : "Maths",
        sub4 : "Science",
        sub5 : "SocialScience",
    },
    {
        id : "UKG",
        sub1 : "Tamil",
        sub2 : "English",
        sub3 : "Maths",
        sub4 : "Science",
        sub5 : "SocialScience",
    },
    {
        id : "11",
        group : "Biology",
        sub1 : "Tamil",
        sub2 : "English",
        sub3 : "Maths",
        sub4 : "Chemistry",
        sub5 : "Physics",
        sub6 : "Biology"
    },
    {
        id : "11",
        group : "Computer Science",
        sub1 : "Tamil",
        sub2 : "English",
        sub3 : "Maths",
        sub4 : "Chemistry",
        sub5 : "Physics",
        sub6 : "ComputerScience"
    },
    {
        id : "11",
        group : "Computer Commerce",
        sub1 : "Tamil",
        sub2 : "English",
        sub3 : "Accounts",
        sub4 : "Economics",
        sub5 : "Commerce",
        sub6 : "ComputerScience"
    },
    {
        id : "12",
        group : "Biology",
        sub1 : "Tamil",
        sub2 : "English",
        sub3 : "Maths",
        sub4 : "Chemistry",
        sub5 : "Physics",
        sub6 : "Biology"
    },
    {
        id : "12",
        group : "Computer Science",
        sub1 : "Tamil",
        sub2 : "English",
        sub3 : "Maths",
        sub4 : "Chemistry",
        sub5 : "Physics",
        sub6 : "Computer Science"
    },
    {
        id : "12",
        group : "Commerce",
        sub1 : "Tamil",
        sub2 : "English",
        sub3 : "Accounts",
        sub4 : "Economics",
        sub5 : "Commerce",
        sub6 : "Computer Science"
    },
]

export default Mark